### ISSUE TITLE
NullPointerException thrown when StoreProperties ID is set to null

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#1398]
final StoreProperties properties = new StoreProperties();
properties.setId(null);

java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at uk.gov.gchq.gaffer.store.StoreProperties.set(StoreProperties.java:235)
	at uk.gov.gchq.gaffer.store.StoreProperties.setId(StoreProperties.java:243)

**Comment by p013570** [comment]
Merged into develop.
