### ISSUE TITLE
Gaffer 1.0.0-RC4 doesn't work in Wildfly

### ISSUE THREAD

**Issue by cybermaggedon** [gchq/Gaffer#1408]
Don't know if you want feedback on 1.0.0-RC4 yet, but...

I previously had Gaffer running inside Wildfly at version 0.8.4, all was working fine.  With 1.0.0-RC2 and 1.0.0-RC4 I get an error when Wildfly starts and tries to load...

```
Caused by: org.jboss.msc.service.DuplicateServiceException: Service jboss.pojo."org.jboss.netty.internal.LoggerConfigurator".DESCRIBED is already registered
	at org.jboss.msc.service.ServiceRegistrationImpl.setInstance(ServiceRegistrationImpl.java:158)
	at org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:235)
	at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:768)
	at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
```

Tried Wildfly 10 and 11. I'm deploying the accumulo-rest-1.0.0-RC4.war file which is the output of the Gaffer build. Should I be deploying something else?

**Comment by p013570** [comment]
Hi @cybermaggedon,

Thanks for letting us know. We had tested it in tomcat and a version of wildfly and it worked fine. I've just download the latest wildfly version and tested it and yes I get the same error as you. Thank you very much for pointing this out. I'll get it fixed and released ASAP.

**Comment by p013570** [comment]
I've just merged the fix into develop and will release it soon. @cybermaggedon - thanks again for spotting the issue. Let us know if you have any more problems.

**Comment by cybermaggedon** [comment]
Thanks @p013570, will give it a go. Wow, that was quick - you guys are on fire!
