### ISSUE TITLE
Operation Views are not automatically set on nested OperationChains

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1415]
If you execute an operation chain like:

```json
{
   "class": "uk.gov.gchq.gaffer.operation.OperationChain",
   "operations": [
      {
         "class": "uk.gov.gchq.gaffer.operation.OperationChain",
         "operations": [
            {
               "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements"
            },
            {
               "class": "uk.gov.gchq.gaffer.operation.impl.Limit",
               "resultLimit": 1,
               "truncate": true
            }
         ]
      }
   ]
}
```

Then the view in GetAllElements is not populated by the Graph and left as null. The store implementations assume that the View will never be null, so this will cause a null pointer exception to be thrown at some point in the Stores logic. For example on Accumulo:

```
java.lang.NullPointerException
        at uk.gov.gchq.gaffer.accumulostore.key.core.impl.byteEntity.ByteEntityIteratorSettingsFactory.getElementPropertyRangeQueryFilter(ByteEntityIteratorSettingsFactory.java:40)
        at uk.gov.gchq.gaffer.accumulostore.retriever.impl.AccumuloAllElementsRetriever.<init>(AccumuloAllElementsRetriever.java:51)
        at uk.gov.gchq.gaffer.accumulostore.operation.handler.GetAllElementsHandler.doOperation(GetAllElementsHandler.java:41)
        at uk.gov.gchq.gaffer.accumulostore.operation.handler.GetAllElementsHandler.doOperation(GetAllElementsHandler.java:36)
        at uk.gov.gchq.gaffer.accumulostore.operation.handler.GetAllElementsHandler.doOperation(GetAllElementsHandler.java:32)
        at uk.gov.gchq.gaffer.store.Store.handleOperation(Store.java:679)
        at uk.gov.gchq.gaffer.store.operation.handler.OperationChainHandler.doOperation(OperationChainHandler.java:47)
        at uk.gov.gchq.gaffer.store.operation.handler.OperationChainHandler.doOperation(OperationChainHandler.java:35)
        at uk.gov.gchq.gaffer.store.Store.handleOperation(Store.java:679)
        at uk.gov.gchq.gaffer.store.operation.handler.OperationChainHandler.doOperation(OperationChainHandler.java:47)
        at uk.gov.gchq.gaffer.store.operation.handler.OperationChainHandler.doOperation(OperationChainHandler.java:35)
        at uk.gov.gchq.gaffer.store.Store.handleOperation(Store.java:679)
        at uk.gov.gchq.gaffer.store.Store.execute(Store.java:271)
        at uk.gov.gchq.gaffer.store.Store.execute(Store.java:265)
        at uk.gov.gchq.gaffer.graph.Graph._execute(Graph.java:207)
        at uk.gov.gchq.gaffer.graph.Graph.execute(Graph.java:166)
        at uk.gov.gchq.gaffer.rest.service.v2.OperationServiceV2._execute(OperationServiceV2.java:184)
        at uk.gov.gchq.gaffer.rest.service.v2.OperationServiceV2.execute(OperationServiceV2.java:81)
```

The fix is quite simple. In the Graph.updateOperationChainView method we need to recursively call updateOperationChainView for any operation that is an instance of OperationChain.

Something like:

```java
private void updateOperationChainView(final OperationChain<?> operationChain) {
    for (final Operation operation : operationChain.getOperations()) {
        if (operation instanceof OperationChain) {
            updateOperationChainView(((OperationChain) operation));
        } else if (operation instanceof OperationView) {
            final OperationView operationView = (OperationView) operation;
            final View opView;
            if (null == operationView.getView()) {
                opView = config.getView();
            } else if (!operationView.getView().hasGroups()) {
                opView = new View.Builder()
                        .merge(config.getView())
                        .merge(operationView.getView())
                        .build();
            } else {
                opView = operationView.getView();
            }

            opView.expandGlobalDefinitions();
            operationView.setView(opView);
        }
    }
}
```

and we would need some unit tests to check this.

Once this has been fixed, we should be able to run the operation chain (above) in the rest api.

**Comment by p013570** [comment]
For the time being a work around is to manually set a view for all operations you use within a nested operation chain.

E.g:

```json
{
  "class": "uk.gov.gchq.gaffer.operation.OperationChain",
  "operations": [
    {
      "class": "uk.gov.gchq.gaffer.operation.OperationChain",
      "operations": [
        {
          "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements",
          "view": {
            "edges": {
              "edge": {}
            },
            "entities": {
              "entity": {}
            }
          }
        },
        {
          "class": "uk.gov.gchq.gaffer.operation.impl.Limit",
          "resultLimit": 1,
          "truncate": true
        }
      ]
    }
  ]
}
```

**Comment by p013570** [comment]
Merged into develop.
