### ISSUE TITLE
Allow use of namespace for accumulo store

### ISSUE THREAD

**Issue by supamanda** [gchq/Gaffer#2167]
Currently if you try using namespaces with Gaffer on Accumulo by setting the graph id to namespace.tablename it to fails because the '.' is an invalid character.

```
java.lang.IllegalArgumentException: Id is invalid: mynamespace.MyTableId, it must match regex: [a-zA-Z0-9_]*
 at uk.gov.gchq.gaffer.store.library.GraphLibrary.validateId(GraphLibrary.java:282)
 at uk.gov.gchq.gaffer.store.library.GraphLibrary.get(GraphLibrary.java:123)
 at uk.gov.gchq.gaffer.store.library.GraphLibrary.checkExisting(GraphLibrary.java:291) 
 at uk.gov.gchq.gaffer.store.library.GraphLibrary.checkExisting(GraphLibrary.java:287)
 at uk.gov.gchq.gaffer.graph.Graph$Builder.build(Graph.java:866)
 at ...
```

I'm raising this issue to follow on from the discussion on chat, the outcomes of which are:
* The allowed characters for the graphId were limited because of an issue with using '.' for the Parquet store
* Namespaces in accumulo lets you grant namespace level permissions to a user (https://static.javadoc.io/org.apache.accumulo/accumulo-core/1.8.0/org/apache/accumulo/core/security/NamespacePermission.html). That means you could create a namespace and grant your write user permission to create tables only in that namespace rather than having to grant them system level permission instead (ie System.CREATE_TABLE) 
* The namespace option should be added to accumulo store properties

**Comment by d47853** [comment]
Merged into develop
