### ISSUE TITLE
Schema.fromJson() does not support schema directories containing subdirectories

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#2262]
I've been trying to run the [RoadTrafficDataLoader](https://github.com/gchq/Gaffer/blob/master/example/road-traffic/road-traffic-generators/src/main/java/uk/gov/gchq/gaffer/traffic/generator/RoadTrafficDataLoader.java), loading the schema from a directory which contains subdirectories. This results in an exception:
```
Exception in thread "main" uk.gov.gchq.gaffer.data.elementdefinition.exception.SchemaException: Failed to load element definitions from bytes
	at uk.gov.gchq.gaffer.data.elementdefinition.ElementDefinitions$BaseBuilder.json(ElementDefinitions.java:323)
	at uk.gov.gchq.gaffer.data.elementdefinition.ElementDefinitions$BaseBuilder.json(ElementDefinitions.java:285)
	at uk.gov.gchq.gaffer.store.schema.Schema$BaseBuilder.json(Schema.java:531)
	at uk.gov.gchq.gaffer.store.schema.Schema.fromJson(Schema.java:116)
	at uk.gov.gchq.gaffer.traffic.generator.RoadTrafficDataLoader.main(RoadTrafficDataLoader.java:106)
Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.file.Files.read(Files.java:3105)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at uk.gov.gchq.gaffer.data.elementdefinition.ElementDefinitions$BaseBuilder.json(ElementDefinitions.java:314)
	... 4 more
```

Interestingly the REST API doesn't throw such an exception when pointing it at the same directory. Took a look and found that this is because the REST API loads the schema by [calling Graph.Builder().addSchema(Path)](https://github.com/gchq/Gaffer/blob/48579e1e3ff18bfa846a053c2e5603819f9753e4/rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/DefaultGraphFactory.java#L117). This method contains code to recursively walk directories:
https://github.com/gchq/Gaffer/blob/48579e1e3ff18bfa846a053c2e5603819f9753e4/core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java#L842-L851

Compare this to Schema.fromJson(Path), which [RoadTrafficDataLoader](https://github.com/gchq/Gaffer/blob/48579e1e3ff18bfa846a053c2e5603819f9753e4/example/road-traffic/road-traffic-generators/src/main/java/uk/gov/gchq/gaffer/traffic/generator/RoadTrafficDataLoader.java#L106) uses. This doesn't include a recursive call for directories:
https://github.com/gchq/Gaffer/blob/48579e1e3ff18bfa846a053c2e5603819f9753e4/core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/ElementDefinitions.java#L304-L315

**Comment by d47853** [comment]
Merged into develop
