### ISSUE TITLE
Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by unclassified02** [gchq/Gaffer#2502]
I'm using Java SE Development Kit 8 Update 301 (64-bit) and a SingleUseMockAccumuloStore class implementation, as suggested by "TheBasics.java" example, and i get the following error:
`hadoop.util.NativeCodeLoader WARN  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:339)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:281)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:321)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:763)
	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:846)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:167)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1164)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1205)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1383)
	at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:2565)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2576)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2593)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2632)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2614)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:169)
	at org.apache.accumulo.core.client.mock.MockInstance.getDefaultFileSystem(MockInstance.java:75)
	at org.apache.accumulo.core.client.mock.MockInstance.<init>(MockInstance.java:82)
	at uk.gov.gchq.gaffer.accumulostore.MockAccumuloStore.preInitialise(MockAccumuloStore.java:63)
	at uk.gov.gchq.gaffer.accumulostore.SingleUseMockAccumuloStore.preInitialise(SingleUseMockAccumuloStore.java:45)
	at uk.gov.gchq.gaffer.accumulostore.AccumuloStore.initialise(AccumuloStore.java:159)
	at uk.gov.gchq.gaffer.store.Store.createStore(Store.java:262)
	at uk.gov.gchq.gaffer.graph.Graph$Builder.updateStore(Graph.java:1082)
	at uk.gov.gchq.gaffer.graph.Graph$Builder.build(Graph.java:970)
	at eu.pyodimille.sentiment.server.Test.run(Test.java:88)
	at eu.pyodimille.sentiment.server.Test.main(Test.java:33)
`

I tried to modify the pom.xml file to avoid this signature problem in jar files, but without success, please help.

**Comment by n3101** [comment]
@unclassified02 I'm sorry that you have encountered this. We are in the process of removing MockAccumuloStore, SingleUseMockAccumuloStore etc from Gaffer as these were deprecated by Accumulo some while ago and have been removed in Accumulo 2. The last thing we still need to remove are the examples in the doc.  :(   This is on our current to do list. Then we can formally deprecate MockAccumuloStore.

From now on, MiniAccumuloStore is the thing to use. I will see if I can get somebody to post an example here to be going on with.

**Comment by n3101** [comment]
@unclassified02 As you were trying to use SingleUseMockAccumuloStore I should have said there is also a SingleUseMiniAccumuloStore which is probably the nearest equivalent. The person best able to advise on this is out this week unfortunately.

**Comment by unclassified02** [comment]
@n3101 thanks for your responses and your advices, then i'll wait for a working example to use. Meantime best regards.

**Comment by t92549** [comment]
@unclassified02 Hi there, sorry about your problem! If you want to just get Gaffer up and running and test it then I would recommend using a [MapStore](https://gchq.github.io/gaffer-doc/stores/map-store.html) which stores everything in memory. The `store.properties` file would look something like:
```
gaffer.store.class=uk.gov.gchq.gaffer.mapstore.SingleUseMapStore
gaffer.store.properties.class=uk.gov.gchq.gaffer.mapstore.MapStoreProperties
```
If you want to test Accumulo stores without running a full accumulo cluster then I'd point you to the setup in the [docs](https://gchq.github.io/gaffer-doc/stores/accumulo-store.html#accumulo-set-up) which should help you setup a mini accumulo cluster and test that.

**Comment by unclassified02** [comment]
Ok, now it works. Thanks for your help, good coding and keep going.

**Comment by n3101** [comment]
@unclassified02 What did you change to get it to work?

**Comment by unclassified02** [comment]
Now i'm using SingleUseMapStore class as recommended by @n3101
