### ISSUE TITLE
RemoveGraph errors when graphId does not exist

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2880]
**Describe the bug**
`RemoveGraph` returns a 500 on the rest api when graphId does not exist

**Expected behavior**
Gaffer 1 would return false if a graph was not deleted, rather than error. It still returns true if it was deleted

**Stack trace and errors**
```
Caused by: uk.gov.gchq.gaffer.operation.OperationException: Error removing graph: AccumuloStoreEnt
        at uk.gov.gchq.gaffer.federatedstore.operation.handler.impl.FederatedRemoveGraphHandler.doOperation(FederatedRemoveGraphHandler.java:48)
        at uk.gov.gchq.gaffer.federatedstore.operation.handler.impl.FederatedRemoveGraphHandler.doOperation(FederatedRemoveGraphHandler.java:40)
        at uk.gov.gchq.gaffer.store.Store.handleOperation(Store.java:966)
        at uk.gov.gchq.gaffer.store.operation.handler.OperationChainHandler.doOperation(OperationChainHandler.java:49)
        at uk.gov.gchq.gaffer.store.operation.handler.OperationChainHandler.doOperation(OperationChainHandler.java:37)
        at uk.gov.gchq.gaffer.store.Store.handleOperation(Store.java:966)
        at uk.gov.gchq.gaffer.store.Store.execute(Store.java:389)
        at uk.gov.gchq.gaffer.store.Store.execute(Store.java:383)
        at uk.gov.gchq.gaffer.graph.Graph._execute(Graph.java:338)
        at uk.gov.gchq.gaffer.graph.Graph.execute(Graph.java:188)
        at uk.gov.gchq.gaffer.rest.service.v2.AbstractOperationService._execute(AbstractOperationService.java:97)
        ... 55 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at uk.gov.gchq.gaffer.federatedstore.FederatedStoreCache.getAccessFromCache(FederatedStoreCache.java:127)
        at uk.gov.gchq.gaffer.federatedstore.FederatedGraphStorage.remove(FederatedGraphStorage.java:190)
        at uk.gov.gchq.gaffer.federatedstore.FederatedGraphStorage.remove(FederatedGraphStorage.java:182)
        at uk.gov.gchq.gaffer.federatedstore.FederatedStore.remove(FederatedStore.java:293)
        at uk.gov.gchq.gaffer.federatedstore.operation.handler.impl.FederatedRemoveGraphHandler.doOperation(FederatedRemoveGraphHandler.java:46)
        ... 65 more
Caused by: java.lang.NullPointerException
        at uk.gov.gchq.gaffer.federatedstore.FederatedStoreCacheTransient.getAccessFromCache(FederatedStoreCacheTransient.java:117)
        at uk.gov.gchq.gaffer.federatedstore.FederatedStoreCache.getAccessFromCache(FederatedStoreCache.java:124)
        ... 69 more
```

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2898
