### ISSUE TITLE
accumulo-store tests failing on some environments

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#493]
In my development environment, I am seeing test failures when building the accumulo-store module:

<pre><code>shouldAddElementsFromHdfs(gaffer.accumulostore.integration.AddElementsFromHdfsIT)  Time elapsed: 0.377 sec  <<< ERROR!
gaffer.operation.OperationException: Failed to fetch elements from HDFS
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:139)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.<init>(LocalJobRunner.java:163)
    at org.apache.hadoop.mapred.LocalJobRunner.submitJob(LocalJobRunner.java:731)
    at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:241)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1297)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1294)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:1294)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1315)
    at gaffer.accumulostore.operation.hdfs.handler.job.tool.FetchElementsFromHdfsTool.run(FetchElementsFromHdfsTool.java:55)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
    at gaffer.accumulostore.operation.hdfs.handler.AddElementsFromHdfsHandler.fetchElements(AddElementsFromHdfsHandler.java:61)
    at gaffer.accumulostore.operation.hdfs.handler.AddElementsFromHdfsHandler.doOperation(AddElementsFromHdfsHandler.java:45)
    at gaffer.accumulostore.operation.hdfs.handler.AddElementsFromHdfsHandler.doOperation(AddElementsFromHdfsHandler.java:40)
    at gaffer.accumulostore.operation.hdfs.handler.AddElementsFromHdfsHandler.doOperation(AddElementsFromHdfsHandler.java:32)
    at gaffer.store.Store.handleOperation(Store.java:367)
    at gaffer.store.Store.handleOperationChain(Store.java:357)
    at gaffer.store.Store.execute(Store.java:178)
    at gaffer.graph.Graph.execute(Graph.java:131)
    at gaffer.graph.Graph.execute(Graph.java:100)
    at gaffer.accumulostore.integration.AddElementsFromHdfsIT.addElementsFromHdfs(AddElementsFromHdfsIT.java:153)
    at gaffer.accumulostore.integration.AddElementsFromHdfsIT.shouldAddElementsFromHdfs(AddElementsFromHdfsIT.java:78)
Caused by: java.io.IOException: Resource file:/home/user/projects/gaffer/accumulo-store/target/data/splits.txt is not publicly accessable and as such cannot be part of the public cache.
    at org.apache.hadoop.yarn.util.FSDownload.copy(FSDownload.java:259)
    at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:61)
    at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:359)
    at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:357)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
    at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:356)
    at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)</code></pre>

One solution may be to ensure that the resources are located in a directory which has 755 permissions by default (e.g. /tmp on UNIX systems). A similar fix may also be required for Windows environments.

My environment is:

OS: Arch Linux x86_64
Kernel: 4.8.2-1
Java: OpenJDK 1.8.0_112

**Comment by a09631** [comment]
The same issue exists on the environment below:

OS: CentOS Linux release 7.2.1511 (Core)
Kernel: 3.10.0-327.22.2.el7.x86_64
Java: openjdk version "1.8.0_101"

**Comment by p013570** [comment]
Merged into develop.
