### ISSUE TITLE
NullPointerException when creating Graph with missing store class

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#707]
The following code:

     Graph graph = new Graph.Builder()
                .addSchema(new Schema())
                .storeProperties(new StoreProperties())
                .build();

produces

    java.lang.NullPointerException
	  at uk.gov.gchq.gaffer.store.StoreProperties.get(StoreProperties.java:85)
	  at uk.gov.gchq.gaffer.store.StoreProperties.getStoreClass(StoreProperties.java:141)
	  at uk.gov.gchq.gaffer.graph.Graph$Builder.createStore(Graph.java:373)
	  at uk.gov.gchq.gaffer.graph.Graph$Builder.updateStore(Graph.java:352)
	  at uk.gov.gchq.gaffer.graph.Graph$Builder.build(Graph.java:328)

because the store class is not defined. It should throw a more useful exception.

**Comment by gaffer01** [comment]
Merged into develop.
