### ISSUE TITLE
Gaffer 0.6.1 does not work on CDH5 clusters

### ISSUE THREAD

**Issue by ctas582** [gchq/Gaffer#722]
I've been unable to get Gaffer 0.6.1 working when deploying onto a CDH5 cluster. When running scans, the tablet servers log the following exception:

```
exception while doing multi-scan 
	uk.gov.gchq.gaffer.data.elementdefinition.exception.SchemaException: Failed to load element definitions from bytes
		at uk.gov.gchq.gaffer.data.elementdefinition.ElementDefinitions$BaseBuilder.json(ElementDefinitions.java:275)
		at uk.gov.gchq.gaffer.data.elementdefinition.ElementDefinitions$BaseBuilder.json(ElementDefinitions.java:260)
		at uk.gov.gchq.gaffer.store.schema.Schema$BaseBuilder.json(Schema.java:375)
		at uk.gov.gchq.gaffer.store.schema.Schema.fromJson(Schema.java:92)
		at uk.gov.gchq.gaffer.accumulostore.key.impl.AggregatorIterator.validateOptions(AggregatorIterator.java:112)
		at uk.gov.gchq.gaffer.accumulostore.key.impl.AggregatorIterator.init(AggregatorIterator.java:96)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:268)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:237)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:218)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:205)
		at org.apache.accumulo.tserver.tablet.ScanDataSource.createIterator(ScanDataSource.java:193)
		at org.apache.accumulo.tserver.tablet.ScanDataSource.iterator(ScanDataSource.java:127)
		at org.apache.accumulo.core.iterators.system.SourceSwitchingIterator.seek(SourceSwitchingIterator.java:180)
		at org.apache.accumulo.tserver.tablet.Tablet.lookup(Tablet.java:733)
		at org.apache.accumulo.tserver.tablet.Tablet.lookup(Tablet.java:848)
		at org.apache.accumulo.tserver.scan.LookupTask.run(LookupTask.java:113)
		at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: uk.gov.gchq.gaffer.exception.SerialisationException: Build method 'uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition$BaseBuilder#build(0 params) has bad return type (uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition), not compatible with POJO type (uk.gov.gchq.gaffer.store.schema.SchemaEntityDefinition)
		at uk.gov.gchq.gaffer.jsonserialisation.JSONSerialiser.deserialise(JSONSerialiser.java:175)
		at uk.gov.gchq.gaffer.data.elementdefinition.ElementDefinitions$BaseBuilder.json(ElementDefinitions.java:272)
		... 20 more
	Caused by: com.fasterxml.jackson.databind.JsonMappingException: Build method 'uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition$BaseBuilder#build(0 params) has bad return type (uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition), not compatible with POJO type (uk.gov.gchq.gaffer.store.schema.SchemaEntityDefinition)
		at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:272)
		at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:247)
		at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:146)
		at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:305)
		at com.fasterxml.jackson.databind.deser.std.MapDeserializer.createContextual(MapDeserializer.java:242)
		at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:309)
		at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:634)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:438)
		at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:298)
		at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:247)
		at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:146)
		at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:322)
		at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:2990)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2884)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2103)
		at uk.gov.gchq.gaffer.jsonserialisation.JSONSerialiser.deserialise(JSONSerialiser.java:173)
		... 21 more
	Caused by: java.lang.IllegalArgumentException: Build method 'uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition$BaseBuilder#build(0 params) has bad return type (uk.gov.gchq.gaffer.store.schema.SchemaElementDefinition), not compatible with POJO type (uk.gov.gchq.gaffer.store.schema.SchemaEntityDefinition)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.buildBuilderBased(BeanDeserializerBuilder.java:383)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBuilderBasedDeserializer(BeanDeserializerFactory.java:344)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBuilderBasedDeserializer(BeanDeserializerFactory.java:180)
		at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:347)
		at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267)
		... 36 more
```

The switch to deserialising schemas using builders might be triggering this bug: https://github.com/FasterXML/jackson-databind/issues/761. Although the Gaffer iterators jar includes a later version of jackson that is unaffected by this issue, the CDH5 distribution of Hadoop includes jackson-core-2.2.3.jar and jackson-databind-2.2.3.jar in the mapreduce lib directory, which appears earlier on Accumulo's classpath so gets used instead.

**Comment by ctas582** [comment]
This commit fixes the issue by ensuring that the iterators always run with the version of Jackson that they have been developed against, rather than the version that is in the Hadoop lib directories.

**Comment by gaffer01** [comment]
Merged into develop.

**Comment by p013570** [comment]
We need to apply the same shading to the library modules, e.g https://github.com/gchq/Gaffer/blob/develop/library/bitmap-library/pom.xml

**Comment by gaffer01** [comment]
Merged into develop.

**Comment by p013570** [comment]
## Migration Steps
The side effect of shading the iterators jar means any other custom jars containing serialisers/functions that is added to Accumulo's classpath that uses jackson will also need to be shaded in the same way. You will need to add something similar to this in your pom:

```xml
<plugin>
    <artifactId>maven-shade-plugin</artifactId>
    <version>${shade.plugin.version}</version>
    <executions>
        <execution>
            <id>iterators</id>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <shadedArtifactAttached>true
                </shadedArtifactAttached>
                <shadedClassifierName>iterators
                </shadedClassifierName>
                <artifactSet>
                    <includes>
                        <include>[your package name]*</include>
                </artifactSet>
                <relocations>
                    <relocation>
                        <pattern>com.fasterxml.jackson</pattern>
                        <shadedPattern>
                            uk.gov.gchq.gaffer.shaded.com.fasterxml.jackson
                        </shadedPattern>
                    </relocation>
                </relocations>
            </configuration>
        </execution>
    </executions>
</plugin>
```
